image:
  repository: infralightio/flytube
  tag: latest
  pullPolicy: Always

env:
  user: "< SUPPLIED BY FIREFLY TEAM >"
  remoteHost: "firefly-relay.firefly.ai"
  targetHost: "< SUPPLIED BY FIREFLY TEAM >"
  remotePort: "22"
  sourcePort: "< SUPPLIED BY FIREFLY TEAM >"
  targetPort: "443"
  sleepDuration: 5

resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
